fix: change parse git action script

diff --git a/.github/workflows/scheduled-task.yml b/.github/workflows/scheduled-task.yml
--- a/.github/workflows/scheduled-task.yml
+++ b/.github/workflows/scheduled-task.yml
@@ -2,8 +2,8 @@ name: Scheduled Task
 
 on:
   schedule:
-    - cron: '30 5 * * 1' # кожного понеділка о 5:30 ранку
-  workflow_dispatch: # дозволяє запускати вручну через інтерфейс GitHub
+    - cron: '30 5 * * 1' # Кожного понеділка о 5:30 ранку
+  workflow_dispatch: # Дозволяє запускати вручну через інтерфейс GitHub
 
 jobs:
   run-script:
@@ -12,11 +12,23 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      - name: Get OAuth Token
-        id: oauth
-        run: echo "::set-output name=token::${{ secrets.OAUTH_TOKEN }}"
+      - name: Authenticate and Get Token
+        id: auth
+        run: |
+          response=$(curl -X POST "https://github.com/login/oauth/access_token" \
+            -H "Accept: application/json" \
+            -d "client_id=${{ secrets.GH_CLIENT_ID }}" \
+            -d "client_secret=${{ secrets.GH_CLIENT_SECRET }}" \
+            -d "code=${{ secrets.GH_PAT }}" \
+            -d "redirect_uri=https://installsat.fun/api/auth/callback/github")
+          echo "Server Response: $response"
+          token=$(echo $response | jq -r '.access_token')
+          if [[ "$token" == "null" ]]; then
+            echo "Authentication failed. Token not received."
+            exit 1
+          fi
+          echo "::set-output name=token::$token"
 
       - name: Call Parse Script
         run: |
-          token="${{ steps.oauth.outputs.token }}"
-          curl -H "Authorization: Bearer $token" -X GET https://installsat.fun/guru/parse/trans-news
+          curl -H "Authorization: Bearer ${{ steps.auth.outputs.token }}" -X GET https://installsat.fun/guru/parse/trans-news
