feat: change github actioin parse job script

diff --git a/.github/workflows/scheduled-task.yml b/.github/workflows/scheduled-task.yml
--- a/.github/workflows/scheduled-task.yml
+++ b/.github/workflows/scheduled-task.yml
@@ -9,16 +9,23 @@ jobs:
   run-script:
     runs-on: ubuntu-latest
     steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
       - name: Authenticate and Get Token
         id: auth
         run: |
-          response=$(curl -X POST https://installsat.fun/login -H "Content-Type: application/json" -d '{"login-email": "${{ secrets.LOGIN_EMAIL }}", "login-password": "${{ secrets.LOGIN_PASSWORD }}"}')
+          response=$(curl -X POST https://installsat.fun/api/auth/callback/credentials \
+            -H "Content-Type: application/json" \
+            -d "{\"login-email\": \"${{ secrets.LOGIN_EMAIL }}\", \"login-password\": \"${{ secrets.LOGIN_PASSWORD }}\"}")
           echo "Server Response: $response"
           token=$(echo $response | jq -r '.token')
+          if [[ "$token" == "null" ]]; then
+            echo "Authentication failed. Token not received."
+            exit 1
+          fi
           echo "::set-output name=token::$token"
 
       - name: Call Parse Script
         run: |
           curl -H "Authorization: Bearer ${{ steps.auth.outputs.token }}" -X GET https://installsat.fun/guru/parse/trans-news
-        env:
-          TOKEN: ${{ steps.auth.outputs.token }}
