fix: change parse git action script

diff --git a/.github/workflows/scheduled-task.yml b/.github/workflows/scheduled-task.yml
--- a/.github/workflows/scheduled-task.yml
+++ b/.github/workflows/scheduled-task.yml
@@ -12,23 +12,13 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      - name: Authenticate and Get Token
-        id: auth
-        run: |
-          response=$(curl -X POST "https://github.com/login/oauth/access_token" \
-            -H "Accept: application/json" \
-            -d "client_id=${{ secrets.GH_CLIENT_ID }}" \
-            -d "client_secret=${{ secrets.GH_CLIENT_SECRET }}" \
-            -d "code=${{ secrets.GH_PAT }}" \
-            -d "redirect_uri=https://installsat.fun/api/auth/callback/github")
-          echo "Server Response: $response"
-          token=$(echo $response | jq -r '.access_token')
-          if [[ "$token" == "null" ]]; then
-            echo "Authentication failed. Token not received."
-            exit 1
-          fi
-          echo "::set-output name=token::$token"
-
       - name: Call Parse Script
         run: |
-          curl -H "Authorization: Bearer ${{ steps.auth.outputs.token }}" -X GET https://installsat.fun/guru/parse/trans-news
+          session_token="${{ secrets.OAUTH_TOKEN }}"
+          echo "Using session token: $session_token"
+          response=$(curl -H "Authorization: Bearer $session_token" -X GET https://installsat.fun/guru/parse/trans-news)
+          echo "Server Response: $response"
+          if [[ "$response" == *"login?callbackUrl"* ]]; then
+            echo "Authentication failed. Redirected to login page."
+            exit 1
+          fi
